version = "1.0"

[main]
name = "Invidious configuration"
services = ["__APP__"]

    [main.config]
    name = "Configuration Options"

        [main.config.registration_enabled]
        ask = "Enable registration"
        type = "boolean"
        yes = "true"
		no = "false"
        help = "Allow/Forbid Invidious (local) account creation"
        bind = "registration_enabled:__INSTALL_DIR__/config/config.yml"

        [main.config.login_enabled]
        ask = "Enable login"
        type = "boolean"
        yes = "true"
		no = "false"
        help = "Allow/Forbid users to log-in"
        bind = "login_enabled:__INSTALL_DIR__/config/config.yml"

        [main.config.captcha_enabled]
        ask = "Enable captcha"
        type = "boolean"
        yes = "true"
		no = "false"
        help = "Enable/Disable the captcha challenge on the login page"
        bind = "captcha_enabled:__INSTALL_DIR__/config/config.yml"