test_format = 1.0

[default]

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.028a4f13db27b12f7c3162a1d0e596e25e1af15f.name = "Upgrade from #153"
