test_format = 1.0

[default]

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.3d152f7a59ef0b2a44747999bab0f3bc6e66c1dc.name = "Upgrade from 24.08.23~ynh1"
