#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================

key=$(ynh_string_random --length=24)
registration_enabled="true"
login_enabled="true"
captcha_enabled="true"
enable_user_notifications="true"
banner=""

#=================================================
# STORE SETTINGS FROM MANIFEST
#=================================================
ynh_script_progression "Storing installation settings..."

ynh_app_setting_set --key=key --value="$key"
ynh_app_setting_set --key=registration_enabled --value=$registration_enabled
ynh_app_setting_set --key=login_enabled --value=$login_enabled
ynh_app_setting_set --key=captcha_enabled --value=$captcha_enabled
ynh_app_setting_set --key=enable_user_notifications --value=$enable_user_notifications
ynh_app_setting_set --key=banner --value="$banner"

#=================================================
# INSTALL DEPENDENCIES
#=================================================
ynh_script_progression "Installing dependencies..."

ynh_hide_warnings curl -fsSL https://crystal-lang.org/install.sh | bash -s -- --channel=stable

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

mkdir -p "$install_dir"
chown -R "$app:www-data" "$install_dir"
git config --system --add safe.directory "$install_dir"

# Download, check integrity, uncompress and patch the source from GitHub
# note: we can't use resources.sources instead of git because Invidious is
# expecting to be in a git environment for the building step...
# see: https://github.com/YunoHost-Apps/invidious_ynh/pull/127
git clone https://github.com/iv-org/invidious "$install_dir" --quiet

pushd "$install_dir"
	git reset --hard --quiet "$version_commit"
	make
popd

chmod -R o-rwx "$install_dir"
chown -R "$app:www-data" "$install_dir"

#=================================================
# MODIFY A CONFIG FILE
#=================================================
ynh_script_progression "Updating configuration..."

ynh_config_add --template="config.yml" --destination="$install_dir/config/config.yml"

chmod 600 "$install_dir/config/config.yml"

#=================================================
# INSTALL INVIDIOUS
#=================================================
ynh_script_progression "Building Invidious.. (this will take some time and resources!)"

pushd "$install_dir"
	./invidious --migrate
popd

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app ..."

# Create a dedicated NGINX config
ynh_config_add_nginx

ynh_config_add --template="cron_invidious" --destination="/etc/cron.d/$app"

ynh_config_add_logrotate

ynh_config_add_systemd

yunohost service add "$app" --description="Invidious is an alternative front-end to YouTube" --log="/var/log/$app/$app.log"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action=start --log_path=systemd

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of Invidious completed"
