#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="$app" --action=stop --log_path=systemd

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression "Ensuring downward compatibility..."

ynh_app_setting_set_default --key=registration_enabled --value="true"
ynh_app_setting_set_default --key=login_enabled --value="true"
ynh_app_setting_set_default --key=captcha_enabled --value="true"
ynh_app_setting_set_default --key=key --value=$(ynh_string_random --length=24)
ynh_app_setting_set_default --key=enable_user_notifications --value="true"
ynh_app_setting_set_default --key=banner --value=""

#=================================================
# UPGRADE DEPENDENCIES
#=================================================
ynh_script_progression "Upgrading dependencies..."

ynh_hide_warnings curl -fsSL https://crystal-lang.org/install.sh | bash -s -- --channel=stable

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

pushd "$install_dir"
	chown -R "$app:www-data" "$install_dir"
	git config --system --add safe.directory "$install_dir"
	ynh_exec_as_app git config pull.rebase false

	ynh_exec_as_app git fetch
   	#git checkout master
   	ynh_exec_as_app git reset --hard --quiet "$version_commit"
	ynh_exec_as_app git pull
	ynh_hide_warnings shards install --production
	ynh_hide_warnings crystal build "$install_dir/src/invidious.cr" --release
popd

chmod -R o-rwx "$install_dir"
chown -R "$app:www-data" "$install_dir"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

# Create a dedicated NGINX config
ynh_config_add_nginx

ynh_config_add_systemd

ynh_config_add --template="cron_invidious" --destination="/etc/cron.d/$app"

ynh_config_add_logrotate

yunohost service add "$app" --description="Invidious is an alternative front-end to YouTube" --log="/var/log/$app/$app.log"

#=================================================
# MODIFY A CONFIG FILE
#=================================================
ynh_script_progression "Updating configuration..."

ynh_config_add --template="config.yml" --destination="$install_dir/config/config.yml"

chmod 600 "$install_dir/config/config.yml"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action=restart --log_path=systemd

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of Invidious completed"
